server:
  port: 8080
  tomcat:
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB

spring:
  application:
    name: afet-vaka-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Flyway kullanılacağı için validate modunda bırakılır
    show-sql: true
    properties:
      hibernate:
        default_schema: afet
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    clean-disabled: false
    clean-on-validation-error: true
    baseline-on-migrate: true
    default-schema: afet
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: h92075143@gmail.com
    password: enff gaww tqoi xuue
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Konfigürasyonu (Uygulama İçi)
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # TODO: Production'da kesinlikle değiştirilecek
    expiration-ms: 86400000 # 24 saat (Access Token)
    refresh-expiration-ms: 28800000 # 8 saat (Refresh Token)
